version: '3'
services:


  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/pgsql/data
    env_file:
      - .env
