# Generated by Django 4.0.10 on 2024-02-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_date_birth_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
