# Generated by Django 4.0.10 on 2024-02-08 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_subscriber_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subscriber',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
