# Generated by Django 4.0.10 on 2024-02-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscriber',
        ),
    ]
