# Generated by Django 4.0.10 on 2024-02-08 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_read',
        ),
        migrations.AddField(
            model_name='post',
            name='read_by_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
