# Generated by Django 4.0.10 on 2024-02-08 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_post_is_read_post_read_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_by_users',
            field=models.ManyToManyField(blank=True, related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
